package com.jungle.dianping.dal;

import com.jungle.dianping.model.UserModel;
import org.apache.ibatis.annotations.Param;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Apr 25 16:00:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Apr 25 16:00:14 CST 2020
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Apr 25 16:00:14 CST 2020
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Apr 25 16:00:14 CST 2020
     */
    UserModel selectByPrimaryKey(Integer id);

    /**
     * 通过手机和密码查询
     */
    UserModel selectByTelphoneAndPassword(@Param("telphone") String telphone, @Param("password")String password);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Apr 25 16:00:14 CST 2020
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Apr 25 16:00:14 CST 2020
     */
    int updateByPrimaryKey(UserModel record);

    /**
     * 查询用户数量
     */
    Integer countAllUser();
}
